---
title: "Data Mining Text Mining Final Project"
author: "Madison Yonash"
date: "2023-10-30"
output:
  html_document:
    df_print: paged
---
# Preprocessing and Initial Steps

```{r}
#Load Packages
library(tidyverse)
library(taylor)
library(tidytext)
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(textdata)
library(knitr)
library(kableExtra)
library(formattable)
library(gridExtra)
library(ggrepel)
library(radarchart)
```

```{r} 
#Create variable for songs being analyzed
songs <- taylor_album_songs
```

```{r}
#View dataset
glimpse(songs)
```

```{r}
#Create tidy dataset for text analysis
my_words <- c("oh","ooh","eh","ha","mmm","mm", "yeah","ah","hey","eeh","uuh","uh","la","da","di","ra","huh","hu","whoa","gonna","wanna","gotta","em")

tidy_taylor <-
  taylor_album_songs  %>% 
  unnest(lyrics)  %>%  
  unnest_tokens(word, lyric) %>% 
  filter(!word %in% my_words) %>% #Remove undesirables
  filter(!nchar(word) < 3) %>% #Words like "ah" or "oo" used in music
  anti_join(stop_words)

glimpse(tidy_taylor)
```
## EDA

```{r}
#View most used words in different songs
tidy_taylor %>% 
    anti_join(get_stopwords())  %>%  
    count(track_name, word, sort = TRUE)
```

```{r}
#Create a word cloud to visualize frequent words
#Creating list of stop words to exclude
word <- c("oh","ooh","eh","ha","mmm","mm", "yeah","ah","hey","eeh","uuh","uh","la","da","di","ra","huh","hu","whoa","gonna","wanna","gotta","em")
lexicon <- c(rep("mine",length(word)))
mystopwords <- cbind(word,lexicon)
mystopwords <- rbind(stop_words,mystopwords)
  
#Data preparation
lyric_tokens <- songs %>% 
  select(lyrics) %>% 
  unnest(lyrics)  %>%
  unnest_tokens(input = lyric , output = "word") %>% 
  count(word,sort=TRUE) %>% 
  anti_join(mystopwords,by="word") %>%
  filter(n>10)

#Word cloud
wordcloud(words = lyric_tokens$word,
          freq = lyric_tokens$n,
          scale = c(4,.5),
          max.words = 150,
          colors = "#B59410"
           ) 
```
# Sentiment Analysis

## Preprocessing
```{r}
#Preparing sentiment analysis lexicons
new_sentiments <- get_sentiments("afinn")
names(new_sentiments)[names(new_sentiments) == 'value'] <- 'score'
new_sentiments <- new_sentiments %>% mutate(lexicon = "afinn", sentiment = ifelse(score >= 0, "positive", "nega1tive"),
                                                     words_in_lexicon = n_distinct((word)))
```

```{r}
#Prepare dataset for sentiment analysis with different lexicons
bing_taylor <- tidy_taylor %>%
  inner_join(get_sentiments("bing"))

nrc_taylor <- tidy_taylor %>%
  inner_join(get_sentiments("nrc"))

nrc_sub_taylor <- tidy_taylor %>%
  inner_join(get_sentiments("nrc")) %>%
  filter(!sentiment %in% c("positive", "negative"))
```
## Entire Discography
```{r}
#Plot Swift's discography using NRC lexicon
nrc_plot <- nrc_taylor %>%
  group_by(sentiment) %>%
  summarise(word_count = n()) %>%
  ungroup() %>%
  mutate(sentiment = reorder(sentiment, word_count)) %>%
  #Use `fill = -word_count` to make the larger bars darker
  ggplot(aes(sentiment, word_count, fill = -word_count)) +
  geom_col() +
  guides(fill = FALSE) + #Turn off the legend
  labs(x = NULL, y = "Word Count") +
  scale_y_continuous(limits = c(0, 3000)) + #Hard code the axis limit
  ggtitle("Taylor Swift NRC Sentiment") +
  theme_minimal() +
  coord_flip()

nrc_plot + scale_fill_taylor_c(album = "Fearless (Taylor's Version)")
```

```{r}
#Plot Swift's discography using Bing lexicon
bing_plot <- bing_taylor %>%
  group_by(sentiment) %>%
  summarise(word_count = n()) %>%
  ungroup() %>%
  mutate(sentiment = reorder(sentiment, word_count)) %>%
  ggplot(aes(sentiment, word_count, fill = sentiment)) +
  geom_col() +
  guides(fill = FALSE) +
  scale_fill_manual(values=c("#eedba9", "#ac844c")) +
  theme_minimal() +
  labs(x = NULL, y = "Word Count") +
  scale_y_continuous(limits = c(0, 3000)) +
  ggtitle("Taylor Swift Bing Sentiment") +
  coord_flip()

bing_plot 
```

```{r}
#Look at polarity and positivity of discography

taylor_polarity_chart <- bing_taylor %>%
  count(sentiment, album_name) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(polarity = positive - negative,
    percent_positive = positive / (positive + negative) * 100)

#Percent positive by chart
pos_chart <- taylor_polarity_chart %>%
  ggplot( aes(x = factor(album_name, album_levels), percent_positive, fill = album_name)) +
  geom_col() +
  scale_fill_taylor_d(album = "Fearless (Taylor's Version)") +
  geom_hline(yintercept = 0) +
  theme_minimal() + theme(plot.title = element_text(size = 11)) +
  xlab(NULL) + ylab(NULL) +
  ggtitle("Percent Positive By Album") +
  theme(legend.position = "none") +
  coord_flip()

pos_chart

```

```{r}
#Polarity by chart
polarity_chart <- taylor_polarity_chart %>%
  ggplot( aes(x = factor(album_name, album_levels), polarity, fill = album_name)) +
  geom_col() +
  scale_fill_taylor_d(album = "Fearless (Taylor's Version)") +
  geom_hline(yintercept = 0) +
  theme_minimal() + theme(plot.title = element_text(size = 11)) +
  xlab(NULL) + ylab(NULL) +
  ggtitle("Polarity By Album") +
  theme(legend.position = "none") +
  coord_flip()

polarity_chart
```

## Albums
```{r}
#Get the count of words per sentiment per album
album_sentiment_nrc <- nrc_sub_taylor %>%
  group_by(album_name, sentiment) %>%
  count(album_name, sentiment) %>%
  select(album_name, sentiment, sentiment_album_count = n)

#Get the total count of sentiment words per album (not distinct)
total_sentiment_album <- nrc_sub_taylor %>%
  count(album_name) %>%
  select(album_name, album_total = n)

#Join the two and create a percent field
album_radar_chart <- album_sentiment_nrc %>%
  inner_join(total_sentiment_album, by = "album_name") %>%
  mutate(percent = sentiment_album_count / album_total * 100 ) %>%
  filter(album_name %in% album_levels) %>%
  select(-sentiment_album_count, -album_total) %>%
  spread(album_name, percent) %>%
  chartJSRadar(showToolTipLabel = TRUE,
               main = "NRC Album Radar")
album_radar_chart
```

```{r}
#Additional comparison of NRC lexicon on albums
nrc_sub_taylor %>%
  filter(album_name %in% c("Taylor Swift", "Fearless (Taylor's Version)", "Speak Now",
                           "Red (Taylor's Version)", "1989", "reputation",
                           "Lover", "folklore", "evermore", "Midnights")) %>%
  count(album_name, sentiment, album_release) %>%
  mutate(sentiment = reorder(sentiment, n), album_name = reorder(album_name, n)) %>%
  ggplot(aes(sentiment, n, fill = sentiment)) +
  geom_col() +
  facet_wrap(factor(album_name, album_levels) ~ album_release, scales = "free_x") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(x = NULL, y = NULL) +
  ggtitle("NRC Sentiment Album Analysis") +
  coord_flip() +
  theme(legend.position = "none")  +
  scale_fill_taylor_d(album = "Fearless (Taylor's Version)")
```


## Track Fives

```{r}
#Examining the feelings in track fives
tidy_taylor %>%
  filter(track_number %in% '5') %>%
  distinct(word) %>%
  inner_join(get_sentiments("nrc")) %>%
  ggplot(aes(x = word, fill = sentiment)) +
  facet_grid(~sentiment) +
  geom_bar() + #Create a bar for each word per sentiment
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        axis.text.x = element_blank()) + #Place the words on the y-axis
  xlab(NULL) + ylab(NULL) +
  ggtitle("Track 5 Sentiment Words") +
  theme(legend.position = "none")  +
  coord_flip() +
  scale_fill_taylor_d(album = "Fearless (Taylor's Version)")
```

```{r}
#Narrow focus to All Too Well
tidy_taylor %>%
  filter(track_name %in% "All Too Well (Taylor's Version)") %>%
  distinct(word) %>%
  inner_join(get_sentiments("nrc")) %>%
  ggplot(aes(x = word, fill = sentiment)) +
  facet_grid(~sentiment) +
  geom_bar() + #Create a bar for each word per sentiment
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        axis.text.x = element_blank()) + #Place the words on the y-axis
  xlab(NULL) + ylab(NULL) +
  ggtitle("All Too Well Sentiment Words") +
  theme(legend.position = "none")  +
  coord_flip() +
  scale_fill_taylor_d(album = "Fearless (Taylor's Version)")
  
```


```{r}
#Comparison of track fives
nrc_sub_taylor %>%
  filter(track_name %in% c("tolerate it", "All You Had To Do Was Stay", "Dear John",
                     "All Too Well (Taylor's Version)", "White Horse (Taylor's Version)", "Delicate", 
                     "The Archer", "You're On Your Own, Kid", "my tears ricochet", "Cold As You")) %>%
  count(track_name, sentiment, album_name) %>%
  mutate(sentiment = reorder(sentiment, n), track_name = reorder(track_name, n)) %>%
  ggplot(aes(sentiment, n, fill = sentiment)) +
  geom_col() +
  facet_wrap(factor(album_name, album_levels) ~ track_name, scales = "free_x") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(x = NULL, y = NULL) +
  ggtitle("NRC Sentiment Track Five Analysis") +
  coord_flip() +
  theme(legend.position = "none")  +
  scale_fill_taylor_d(album = "Fearless (Taylor's Version)")
```

